language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_script:
  - npm install -g gulp
  - npm install -g gulp-util
  - npm install -g nw-builder
script: gulp
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec